-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 23:22:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sale_point
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sale_point
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sale_point` DEFAULT CHARACTER SET utf8 ;
USE `sale_point` ;

-- -----------------------------------------------------
-- Table `sale_point`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sale_point`.`sales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sale_point`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sale_point`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codebar` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `stock` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `codebar_UNIQUE` (`codebar` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sale_point`.`sold_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sale_point`.`sold_products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sales_id` INT UNSIGNED NOT NULL,
  `products_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sold_products_products_idx` (`products_id` ASC),
  INDEX `fk_sold_products_sales1_idx` (`sales_id` ASC),
  CONSTRAINT `fk_sold_products_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `sale_point`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sold_products_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `sale_point`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sale_point`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sale_point`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(32) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `can_sell` TINYINT(1) UNSIGNED NOT NULL,
  `can_buy` TINYINT(1) UNSIGNED NOT NULL,
  `can_inventory` TINYINT(1) UNSIGNED NOT NULL,
  `can_check_stock` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sale_point`.`user_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sale_point`.`user_sales` (
  `sale_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  INDEX `fk_user_sales_sales1_idx` (`sale_id` ASC),
  INDEX `fk_user_sales_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `sale_id_UNIQUE` (`sale_id` ASC),
  CONSTRAINT `fk_user_sales_sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `sale_point`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_sales_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sale_point`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
